// Hometown Realitor: Neighborhood Themes & Building Styles Configuration

export const BUILDING_STYLES = {
  TINY_MANSION: {
    id: 'TINY_MANSION',
    label: 'Tiny Home ➔ Luxury Mansion',
    desc: 'Starts with modern Tiny Homes and culminates in a Grand Luxury Mansion.',
    singleName: 'Tiny Home',
    singlePlural: 'Tiny Homes',
    topName: 'Luxury Mansion',
    singleIcon: '🛖',
    topIcon: '🏰'
  },
  RV_RESORT: {
    id: 'RV_RESORT',
    label: 'RV Park ➔ Glamping Resort',
    desc: 'Starts with Camper / RV Lots and upgrades to a Premier Glamping Resort / Trailer Park.',
    singleName: 'RV Lot',
    singlePlural: 'RV Lots',
    topName: 'Glamping Resort',
    singleIcon: '🏕️',
    topIcon: '🏖️'
  },
  COTTAGE_ESTATE: {
    id: 'COTTAGE_ESTATE',
    label: 'Bungalow ➔ Grand Estate',
    desc: 'Classic neighborhood progression from suburban Bungalows to a private Gated Estate.',
    singleName: 'Bungalow',
    singlePlural: 'Bungalows',
    topName: 'Grand Estate',
    singleIcon: '🏡',
    topIcon: '🏛️'
  },
  URBAN_HIGHRISE: {
    id: 'URBAN_HIGHRISE',
    label: 'Walkup Apartment ➔ Sky Penthouse',
    desc: 'High-density urban neighborhood from brick Walkup Apartments to a Sky Penthouse.',
    singleName: 'Apartment',
    singlePlural: 'Apartments',
    topName: 'Sky Penthouse',
    singleIcon: '🏢',
    topIcon: '🏙️'
  }
};

export const NEIGHBORHOOD_PRESETS = {
  HOMETOWN_USA: {
    id: 'HOMETOWN_USA',
    label: 'Hometown USA (Suburban Streets)',
    desc: 'Classic American town with tree-lined streets, local transit, and community squares.',
    spaces: {
      0: 'PAYDAY',
      1: 'Maple Street',
      2: 'City Council',
      3: 'Elm Avenue',
      4: 'HOA Annual Dues',
      5: 'Downtown Express Bus',
      6: 'Oak Lane',
      7: 'Travel',
      8: 'Cedar Boulevard',
      9: 'Pine Way',
      10: 'City Hall / Detained',
      11: 'Walnut Street',
      12: 'Power & Light Co.',
      13: 'Spruce Avenue',
      14: 'Birch Lane',
      15: 'Crosstown Commuter Rail',
      16: 'Willow Court',
      17: 'City Council',
      18: 'Cypress Drive',
      19: 'Magnolia Way',
      20: 'Town Square',
      21: 'Hickory Street',
      22: 'Travel',
      23: 'Sycamore Avenue',
      24: 'Chestnut Boulevard',
      25: 'North Suburban Rail',
      26: 'Ash Way',
      27: 'Beech Street',
      28: 'Municipal Water Works',
      29: 'Poplar Avenue',
      30: 'Report to City Hall',
      31: 'Alder Lane',
      32: 'Redwood Boulevard',
      33: 'City Council',
      34: 'Juniper Way',
      35: 'Metro Rapid Transit',
      36: 'Travel',
      37: 'Sunset Strip',
      38: 'City Beautification Fee',
      39: 'Grand Boulevard'
    }
  },
  BEACH_TOWN: {
    id: 'BEACH_TOWN',
    label: 'Sunny Beach Bay',
    desc: 'Coastal getaway featuring seaside lanes, boardwalk piers, ferries, and ocean breezes.',
    spaces: {
      0: 'PAYDAY',
      1: 'Driftwood Lane',
      2: 'City Council',
      3: 'Seashell Drive',
      4: 'Coastal Harbor Tax',
      5: 'Bay Ferry Shuttle',
      6: 'Pelican Point',
      7: 'Travel',
      8: 'Sandpiper Cove',
      9: 'Dolphin Way',
      10: 'Coast Guard Station',
      11: 'Coral Reef Way',
      12: 'Tidal Energy Works',
      13: 'Surfside Boulevard',
      14: 'Manta Ray Lane',
      15: 'Island Water Taxi',
      16: 'Lighthouse Point',
      17: 'City Council',
      18: 'Anchorage Way',
      19: 'Sailors Walk',
      20: 'Boardwalk Pavilion',
      21: 'Marlin Avenue',
      22: 'Travel',
      23: 'Breeze Boulevard',
      24: 'Tidepool Terrace',
      25: 'Harbor Coastal Train',
      26: 'Seaside Promenade',
      27: 'Marina Way',
      28: 'Desalination Plant',
      29: 'Sunken Galleon Pier',
      30: 'Detained by Coast Guard',
      31: 'Ocean Boulevard',
      32: 'Palm Beach Way',
      33: 'City Council',
      34: 'Paradise Cove',
      35: 'Airport Sky Ferry',
      36: 'Travel',
      37: 'Millionaires Pier',
      38: 'Yacht Club Assessment',
      39: 'Golden Sands Beach'
    }
  },
  METRO_HEIGHTS: {
    id: 'METRO_HEIGHTS',
    label: 'Downtown Metro Heights',
    desc: 'Bustling metropolis with subway stations, financial avenues, and high-rise avenues.',
    spaces: {
      0: 'PAYDAY',
      1: 'Market Alley',
      2: 'City Council',
      3: 'Warehouse Row',
      4: 'City Business Tax',
      5: 'Central Subway Line',
      6: 'Brewery District',
      7: 'Travel',
      8: 'Cobblestone Way',
      9: 'Canal Street',
      10: 'Municipal Courthouse',
      11: 'Arts District Way',
      12: 'Metro Grid Power',
      13: 'Gallery Row',
      14: 'Theater Plaza',
      15: 'Grand Central Express',
      16: 'Innovation Parkway',
      17: 'City Council',
      18: 'Tech Boulevard',
      19: 'Silicon Avenue',
      20: 'Central Park Green',
      21: 'Museum Way',
      22: 'Travel',
      23: 'Embassy Row',
      24: 'University Plaza',
      25: 'High-Speed Airport Rail',
      26: 'Commerce Street',
      27: 'Lexington Avenue',
      28: 'City Hydro Works',
      29: 'Financial District Way',
      30: 'Summoned to Courthouse',
      31: 'Park Avenue',
      32: '5th Avenue Row',
      33: 'City Council',
      34: 'Skyline Boulevard',
      35: 'Metro Monorail',
      36: 'Travel',
      37: 'Billionaires Row',
      38: 'Luxury Penthouse Surcharge',
      39: 'Crown Summit Towers'
    }
  }
};
